version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: work-hub-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54323:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  redis:
#    image: redis:7
#    container_name: project_redis
#    ports:
#      - "6379:6379"

volumes:
  postgres_data: