version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: work-hub-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "54323:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  zookeeper_market:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper_market
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22183:2181

  kafka_market:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka_market
    depends_on:
      - zookeeper_market
    ports:
      - 29093:29093
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_market:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_market:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop_market:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop_market
    ports:
      - 9005:9000
    environment:
      KAFKA_BROKERCONNECT: kafka_market:9093
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka_market


#  redis:
#    image: redis:7
#    container_name: project_redis
#    ports:
#      - "6379:6379"

volumes:
  postgres_data:
  rabbitmq_data:
