"""add table emails

Revision ID: c5becd53fef1
Revises: 5ac9893e48a1
Create Date: 2025-10-17 14:47:27.360735

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'c5becd53fef1'
down_revision: Union[str, Sequence[str], None] = '5ac9893e48a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
